# FROM tensorflow/tensorflow:latest
FROM    ubuntu:latest

RUN     apt-get update -y
RUN     apt-get upgrade -y

RUN     apt-get install -y python3 python3.12-venv

RUN     python3 -m venv env

# RUN     /env/bin/pip install opencv-python ultralytics
RUN     /env/bin/pip install torch torchvision mmdet

CMD     [ "/bin/bash" ]
